USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS DB_COURSE_PUBLICATIONS;

USE DATABASE  DB_COURSE_PUBLICATIONS;

CREATE SCHEMA IF NOT EXISTS SC_COURSE_PUBLICATIONS;

USE SCHEMA SC_COURSE_PUBLICATIONS;

CREATE TABLE IF NOT EXISTS COURSE_PUBLICATIONS(
    CP_COURSE_ID NUMBER(20, 0) NOT NULL,
    CP_AUTHOR_SK NUMBER(20, 0) NOT NULL,
    CP_PUBLISHED_TIMESTAMP_SK NUMBER(20, 0) NOT NULL,
    CP_SUBJECT_SK NUMBER(20, 0) NOT NULL,
    CP_IS_PAID BOOLEAN NOT NULL,
    CP_PRICE FLOAT NULL,
    CP_NUM_LECTURES NUMBER(20, 0) NOT NULL,
    CP_NUM_REVIEWS NUMBER(20, 0) NULL,
    CP_NUM_SUBS NUMBER(20, 0) NULL,
    CP_CONTENT_DURATION FLOAT NULL,
    CP_LEVEL_SK NUMBER(20, 0) NOT NULL,
    CP_COURSE_TITLE VARCHAR(100) NOT NULL
);


CREATE TABLE IF NOT EXISTS AUTHOR_DIM(
    A_AUTHOR_SK NUMBER(20, 0) AUTOINCREMENT START 1 INCREMENT 1 NOT NULL PRIMARY KEY,
    A_AUTHOR_ID VARCHAR(100) NOT NULL,
    A_AUTHOR_F_NAME VARCHAR(100) NOT NULL,
    A_AUTHOR_L_NAME VARCHAR(100) NOT NULL,
    A_AUTHOR_CODE VARCHAR(100) NOT NULL
);


CREATE TABLE IF NOT EXISTS SUBJECT_DIM(
    S_SUBJECT_SK NUMBER(20, 0) AUTOINCREMENT START 1 INCREMENT 1 NOT NULL PRIMARY KEY,
    S_SUBJECT VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS LEVEL_DIM(
    L_LEVEL_SK NUMBER(20, 0) AUTOINCREMENT START 1 INCREMENT 1 NOT NULL PRIMARY KEY,
    L_LEVEL VARCHAR(100) NOT NULL
);


CREATE TABLE IF NOT EXISTS PUBLISHED_TIMESTAMP_DIM(
    PT_PUBLISHED_TIMESTAMP_SK NUMBER(20, 0) AUTOINCREMENT START 1 INCREMENT 1 NOT NULL PRIMARY KEY,
    PT_TIMESTAMP VARCHAR(100) NOT NULL,
    PT_DATE DATE NOT NULL,
    PT_DAY NUMBER(20, 0) NOT NULL,
    PT_MONTH NUMBER(20, 0) NOT NULL,
    PT_YEAR NUMBER(20, 0) NOT NULL,
    PT_DAY_SUFFIX VARCHAR(100) NOT NULL,
    PT_WEEK_OF_YEAR NUMBER(20, 0) NOT NULL,
    PT_QUARTER_OF_YEAR NUMBER(20, 0) NOT NULL,
    PT_DAY_OF_WEEK VARCHAR(100) NOT NULL,
    PT_YYYY_MM VARCHAR(100) NOT NULL
);